name: Sail for soldiers
favicon: null
layout_spectrum: 0.50153
typography_spectrum: 0.52164
title: Sailing round the Baltic to raise money for UK charities
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f4ed'
    - '#070908'
    - '#667787'
    - '#a5a5a5'
    - '#e82d21'
  brandStrength: 1
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
