name: Sail for soldiers
favicon: null
layout_spectrum: 0.50153
typography_spectrum: 0.7203558834735304
title: Sailing round the Baltic to raise money for UK charities
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#540000'
    - '#afb1c6'
    - '#414350'
    - '#fef4e3'
    - '#da3400'
  brandStrength: 0.9375
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
