name: Sail for soldiers
favicon: null
layout_spectrum: 0.045743084978312254
typography_spectrum: 0.7203558834735304
title: Sailing round the Baltic to raise money for UK charities
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.008004123345017433
  lightness: 0.3045540018938482
  saturation: 0.047501404536888
  rhythmicContrast: 0.06357260351069272
purpose: []
